# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: TestBasic

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # daily at 3:24 UTC
    - cron: '24 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      # If you want to matrix build , you can append the following list.
      matrix:
        go_version:
          - 1.22
          - 1.23
        os:
          - ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}

    - name: Build
      run: make build
    - name: InstUt
      run: go test -v $(go list -e ./pkg/... | grep -v /rules/ | grep github.com/antgan-0226/opentelemetry-go-auto-instrumentation/pkg/) -coverprofile=coverage.txt -covermode=atomic
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Test
      run: go test -short -timeout 50m -v -run='.*Test[^Plugins|Latest|Muzzle].*' github.com/antgan-0226/opentelemetry-go-auto-instrumentation/test
